export const mouseProduct = [
  {
    id: 1,
    name: 'Logitech G202',
    pic: {
      img1: [require('../../../img/category/mouse/product1/prod1_1.jpg')],
      img2: [require('../../../img/category/mouse/product1/prod1_2.jpg')],
      img3: [require('../../../img/category/mouse/product1/prod1_3.jpg')],
      img4: [require('../../../img/category/mouse/product1/prod1_4.jpg')],
      img5: [require('../../../img/category/mouse/product1/prod1_5.jpg')],
      img6: [require('../../../img/category/mouse/product1/prod1_6.jpg')],
    },
    detail: 'USB 2.0 / 1000 DPI / 3 Buttons',
    price: '500',
  },
  {
    id: 2,
    name: 'Asus Mx89',
    pic: {
      img1: [require('../../../img/category/mouse/product1/prod1_1.jpg')],
      img2: [require('../../../img/category/mouse/product1/prod1_2.jpg')],
      img3: [require('../../../img/category/mouse/product1/prod1_3.jpg')],
      img4: [require('../../../img/category/mouse/product1/prod1_4.jpg')],
      img5: [require('../../../img/category/mouse/product1/prod1_5.jpg')],
      img6: [require('../../../img/category/mouse/product1/prod1_6.jpg')],
    },
    detail: 'USB 2.0 / 1000 DPI / 3 Buttons',
    price: '500',
  },
  {
    id: 3,
    name: 'Razer 696',
    pic: {
      img1: [require('../../../img/category/mouse/product1/prod1_1.jpg')],
      img2: [require('../../../img/category/mouse/product1/prod1_2.jpg')],
      img3: [require('../../../img/category/mouse/product1/prod1_3.jpg')],
      img4: [require('../../../img/category/mouse/product1/prod1_4.jpg')],
      img5: [require('../../../img/category/mouse/product1/prod1_5.jpg')],
      img6: [require('../../../img/category/mouse/product1/prod1_6.jpg')],
    },
    detail: 'USB 2.0 / 1000 DPI / 3 Buttons',
    price: '500',
  },
  {
    id: 4,
    name: 'Lenoveo 999',
    pic: {
      img1: [require('../../../img/category/mouse/product1/prod1_1.jpg')],
      img2: [require('../../../img/category/mouse/product1/prod1_2.jpg')],
      img3: [require('../../../img/category/mouse/product1/prod1_3.jpg')],
      img4: [require('../../../img/category/mouse/product1/prod1_4.jpg')],
      img5: [require('../../../img/category/mouse/product1/prod1_5.jpg')],
      img6: [require('../../../img/category/mouse/product1/prod1_6.jpg')],
    },
    detail: 'USB 2.0 / 1000 DPI / 3 Buttons',
    price: '500',
  },
];
